### ISSUE TITLE
New format for urls file

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#83]
As first discussed in https://github.com/akrennmair/newsbeuter/issues/158, moving `urls` file from plain text to a more sophisticated format like YAML will let us have per-feed settings (as requested in https://github.com/akrennmair/newsbeuter/issues/248, https://github.com/akrennmair/newsbeuter/issues/326, https://github.com/akrennmair/newsbeuter/issues/465, https://github.com/newsboat/newsboat/issues/77, and probably touched on in https://github.com/akrennmair/newsbeuter/issues/176). #77 is fairly recent, and there is also a related discussion on [our mailing list](https://groups.google.com/forum/#!topic/newsboat/dG9ZLHgJF5M), so I'm creating this tracking issue here now.

The first order of business is to decide on the format. ~~Requirements~~ Wishes are:

- format is well-known, or at least exists already (frees us of burden of designing it; potentially some users will already be familiar with it; potentially some text editors will already have support for it);
- there are parsers we can use;
- as little syntax as possible (e.g. JSON has square brackets, curly brackets and commas—easy for programmers, hard for users).

**Comment by gregf** [comment]
As much as I normally prefer toml, I believe yaml is better for this.

**Comment by Minoru** [comment]
Thank you for the analysis! I'll go read the YAML spec to see what pitfalls it has for the non-technical user. The only such pitfall I can see right now is "no tabs for indentation" rule—we'll need to make sure that our parser reacts to this with a friendly message.

**Comment by der-lyse** [comment]
Just for the record. It probably won't affect us very much as the feed config doesn't really benefit from them, but multi-line strings in YAML are a bit… let's say: [scary (you may also want to read through those comments)](https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines/21699210#21699210). Nevertheless, YAML still seems like the best choice suiting our needs.

Until now I've never heard of CSON and it indeed looks even better than YAML.

Hey, why not using XML, Newsboat already has a parser for that?! :-> No, please don't.

**Comment by Minoru** [comment]
I finally read the Preview chapter of the spec.

After reading about [structures in YAML](http://yaml.org/spec/1.2/spec.html#id2760395), I changed my focus from "what pitfalls await the user" to "how much potentially useless things YAML contains" (useless for Newsboat's urls file). I think the answer is "quite a lot": aforementioned structures, complex mapping keys, myriad ways to escape/multiline strings, explicit typing. The only remaining features are structures, scalars, and tags.

TOML has everything but the tags, but we can emulate them in code by adding "settings groups" or something:

```toml
[group.frequent]
reload-time = 1
reload-retries = 1

[group.broken_ssl]
ssl-verifypeer = false

['https://example.com/feed.atom']
groups = [ 'frequent', 'broken_ssl' ]
```

After that, I read TOML spec with the same focus. It's better; potentially useless features are: special handling for dates and time, arrays of tables. There are only four types of strings, which is acceptable I guess.

One inconvenience is that tables use keys for names, and bare keys can only contain ASCII alphanumerics, underscores, and dashes. This means @tsipinakis's example would look slightly differently:

```toml
# feed without any tags
['''https://github.com/newsboat/newsboat/releases.atom''']
# feed with tags and name
['''https://newsboat.org/news.atom''']
name="newsboat.org"
tags="newsboat,news"
#- or, with TOMLs lists
tags=["software", "updates"]
```

One set of quotes might be enough (i.e. `'https://newsboat.org/news.atom'`), but not always; since URLs might contain single quotes (they don't have to be percent-encoded IIRC), it's better to always use triple quotes. Unfortunately for us, this is part of the format, so the parser would hide this detail from us, and we wouldn't be able to enforce it. In other words, that's a pitfall for the user.

I also didn't see any requirement on the order of the tables, i.e. it's not guaranteed that parser will return URLs in the same order as they are in the file. This is a problem because we depend on that order (by default feedlist shows feeds in the same order as they're in the file).

I invite everyone to think hard about things that we might add to urls file and which can't be (conveniently) expressed in TOML.

@gregf, @der-lyse, I'd be glad to see expanded versions of your comments to see what makes you prefer YAML in this case.

**Comment by Minoru** [comment]
To clarify: "useless" features worry me because user might inadvertently trigger them and either get a confusing error message (most likely), or, worse yet, get a valid file that doesn't do what they think it does (highly unlikely, and I struggle to come up with an example such that it would be both valid YAML and acceptable from Newsboat's standpoint). Less is more.

**Comment by der-lyse** [comment]
To start off with, advantages and disadvantages on the YAML vs. TOML topic are very minimalistic in my opinion. But here are my thoughs (later points are just brainstorming, probably not helpful at all, but who knows):

1. TOML indeed does not guarantee in the spec that the tables are ordered. It depends on the actual parser and some of them actually [do preserve the order of definition](https://github.com/toml-lang/toml/issues/162#issuecomment-14334155). So this problem could be considered taken care of, I reckon.
2. I personally dislike being forced to quote strings in any case in configs, it just feels not elegant to me. Of course, nothing major, just very subjective taste. YAML and good old INI on the other hand would let me safe the quotation marks on most situations.
3. Most of my feeds won't have any additional settings, so declaring tons of empty tables seems a bit odd. In contrast to that, YAML arrays read a tiny bit more naturally. Indeed, with the `url` key it's even longer than TOML, so I'm obviously biased as I'm more used to YAML than to TOML (in fact only used INI so far).
4. Speaking of that – watch out, now it's getting sketchy – we may could just allow an abbreviation for that by allowing strings instead of objects:
    ```yaml
    # feed without any tags, just a string and no object
    - https://github.com/newsboat/newsboat/releases.atom

    # feed with tags and name
    - url: https://newsboat.org/news.atom
      name: newsboat.org
      tags: [software, updates] # I definitely prefer using arrays here
    ```
    But of course this makes editing the file harder if one decides to finally add some settings. :-(
5. Another idea: having the URLs as keys, but this makes things even worse, because as far as I know the order of keys in YAML is not guaranteed either and for empty settings an explicit object is required, making it visually unpleasing.
6. Maybe go with a custom DSL? Yes, this defeats the requirement of being already established, so no syntax highlighting for editors out of the box.
